version: 1

formatters:
  simple:
    format: '%(asctime)s:%(levelname)8s:%(name)11s:%(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: $level
    formatter: simple
    stream: ext://sys.stdout

loggers:
  ws:
    level: $level
    handlers: [console]
    propagate: no

root:
  level: $level
  handlers: [console]
